# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://api.paystack.co/balance
Authorization: Bearer sk_live_f119f9bf61e13bd8fac7b7353fa30783d18d384e


###
POST https://api.paystack.co/transferrecipient
Authorization: Bearer sk_live_f119f9bf61e13bd8fac7b7353fa30783d18d384e
Content-Type: application/json
{ 
  "type": "nuban",
  "name": "Omomowo Simeon",
  "account_number": "1445576211",
  "bank_code": "044",
  "currency": "NGN"
}
